name: Ticovan AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt clean
          sudo apt-get update
          sudo apt-get install -y libsdl2-2.0-0
      - name: install pyxel
        run: sudo pip3 install pyxel pyinstaller
      - name: build
        run: |
          pyxel package . ticoban.py
          pyxel app2exe ticoban-pyxel.pyxapp
      - name: Copy files
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/icons
          install -Dm755 ticoban-pyxel AppDir/usr/bin/ticoban
          install -Dm644 icon.png AppDir/usr/share/icons/ticoban.png
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        env:
          UPDATE_INFO: gh-releases-zsync|AppImageCrafters|ticoban|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
