name: Ticovan AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt clean
          sudo apt-get update
          sudo apt-get install -y libsdl2-2.0-0
      - name: install pyxel
        run: sudo pip3 install pyxel pyinstaller
      - name: build
        run: |
          ./build-linux.sh --appimage
      - name: Copy files
        run: |
          install -Dm755 ticoban-pyxel AppDir/usr/bin/ticoban
          mkdir -p mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps/
          install -Dm644 icon.png AppDir/usr/share/icons/hicolor/128x128/apps/ticoban.png
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        with:
          recipe: AppImageBuilder.yml
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
