name: Ticovan AppImage

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'
      - '20*'

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt clean
          sudo apt-get update
          sudo apt-get install -y libsdl2-2.0-0 squashfs-tools
      - name: install pyxel
        run: sudo pip3 install pyxel pyinstaller
      - name: build
        run: |
          ./build-linux.sh --appimage
      - name: Copy files
        run: |
          install -Dm755 ticoban-pyxel AppDir/usr/bin/ticoban
          mkdir -p mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps/
          install -Dm644 icon.png AppDir/usr/share/icons/hicolor/128x128/apps/ticoban.png
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
          UPDATE_INFO: gh-releases-zsync|son-link|ticoban-pyxel|latest|*.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
      - name: Archive AppImage
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: *.AppImage*
  
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage *.AppImage*
